# Generated by Django 3.2.4 on 2021-10-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tutorial', '0003_auto_20211011_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
